title: BSA Troop 370 Documentation
remote_theme: "just-the-docs"
search_enabled: true
aux_links:
    "BSA Troop 370 Website":
      - "https://troop370atlanta.org/"
color_scheme: nil
plugins:
  - jekyll-remote-theme
